server:
  port: 3964
  servlet:
    context-path: /api

spring:

  datasource:
    url: jdbc:mysql://101.43.95.238:3306/rich_resource?serverTimezone=Hongkong&useAffectedRows=true
    username: root
    password: WHL531124
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      max-wait: 60000
      initial-size: 5
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  redis:
    host: 101.43.95.238
    port: 6379
    database: 2
    password: WHL531124
    timeout: 1800000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

releasedao:
  config:
    logger: false
